'use client';

import { AtSign, Clock3, MapPin, Phone, ShieldCheck } from 'lucide-react';
import { PublicHeader } from '@/components/public-header';
import { useCatalog } from '@/components/providers';

const dayNames = ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'];
export default function InformationPage() {
  const { config, development } = useCatalog();
  return <main className="min-h-screen bg-[#fffaf5] text-[#2b1722]"><PublicHeader /><div className="mx-auto max-w-4xl px-4 py-10 sm:px-6"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#a62c63]">A loja</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em]">Informações</h1>{development && <div className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900">Os dados abaixo são de desenvolvimento e precisam ser confirmados no painel antes do lançamento.</div>}<div className="mt-8 grid gap-4 sm:grid-cols-2"><InfoCard icon={MapPin} title="Endereço"><p>{config.address || 'A confirmar'}</p><p>{config.city}</p></InfoCard><InfoCard icon={Phone} title="Contato"><p>{config.phoneDisplay || 'Telefone a confirmar'}</p>{config.whatsappEnabled && <p>WhatsApp habilitado para contato</p>}</InfoCard><InfoCard icon={AtSign} title="Instagram"><p>{config.instagramHandle || 'A confirmar'}</p></InfoCard><InfoCard icon={ShieldCheck} title="Privacidade"><p>{config.privacyNotice || 'Política em revisão antes do lançamento.'}</p></InfoCard></div><section className="mt-4 rounded-[28px] bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-[#fff0f5] text-[#82204f]"><Clock3 className="size-5" /></span><h2 className="text-xl font-black">Horários</h2></div><div className="mt-5 divide-y divide-[#82204f]/8">{config.hours.sort((a, b) => a.day - b.day).map((day) => <div key={day.day} className="flex justify-between gap-4 py-3 text-sm"><strong>{dayNames[day.day]}</strong><span className="text-right text-[#826a75]">{day.closed ? 'Fechado' : day.windows.map((window) => `${window.open} às ${window.close}`).join(' / ')}</span></div>)}</div></section></div></main>;
}
function InfoCard({ icon: Icon, title, children }: { icon: typeof MapPin; title: string; children: React.ReactNode }) { return <section className="rounded-[28px] bg-white p-6 shadow-sm"><span className="grid size-10 place-items-center rounded-full bg-[#fff0f5] text-[#82204f]"><Icon className="size-5" /></span><h2 className="mt-4 text-lg font-black">{title}</h2><div className="mt-2 text-sm leading-relaxed text-[#826a75]">{children}</div></section>; }
