'use client';

import { collection, limit, onSnapshot, orderBy, query, Timestamp } from 'firebase/firestore';
import { Search } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { AdminShell } from '@/components/admin-shell';
import { useAuth } from '@/components/providers';
import { getFirebaseClient, hasFirebaseConfig } from '@/lib/firebase/client';
import { formatBRL, type OrderStatus } from '@/shared/domain';

interface OrderRow { id: string; orderNumber: string; createdAt?: Timestamp; customer: { name: string; whatsapp?: string }; fulfillment: { mode: string }; pricing: { totalCents: number }; status: OrderStatus }
const statusLabel: Record<OrderStatus, string> = { NEW: 'Novo', CONFIRMED: 'Confirmado', PREPARING: 'Em preparo', READY: 'Pronto', OUT_FOR_DELIVERY: 'Saiu para entrega', COMPLETED: 'Concluído', CANCELLED: 'Cancelado' };
const filters: Array<OrderStatus | 'ACTIVE'> = ['ACTIVE', 'NEW', 'CONFIRMED', 'PREPARING', 'READY', 'OUT_FOR_DELIVERY', 'COMPLETED', 'CANCELLED'];
export default function OrdersPage() {
  const { role } = useAuth();
  const [orders, setOrders] = useState<OrderRow[]>([]); const [filter, setFilter] = useState<OrderStatus | 'ACTIVE'>('ACTIVE'); const [search, setSearch] = useState(''); const [error, setError] = useState('');
  useEffect(() => {
    if (!hasFirebaseConfig || !role) return;
    return onSnapshot(query(collection(getFirebaseClient().db, 'orders'), orderBy('createdAt', 'desc'), limit(100)), (snapshot) => setOrders(snapshot.docs.map((item) => ({ id: item.id, ...item.data() }) as OrderRow)), (cause) => setError(cause.message));
  }, [role]);
  const visible = useMemo(() => { const term = search.trim().toLowerCase().replace(/^#/, ''); return orders.filter((order) => { const matchesStatus = filter === 'ACTIVE' ? !['COMPLETED', 'CANCELLED'].includes(order.status) : order.status === filter; if (!matchesStatus || !term) return matchesStatus; return [order.orderNumber, order.id, order.customer.name, order.customer.whatsapp].filter(Boolean).some((value) => String(value).toLowerCase().replace(/^#/, '').includes(term)); }); }, [orders, filter, search]);
  return <AdminShell><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#a62c63]">Operação</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em]">Pedidos</h1><p className="mt-2 text-sm text-[#826a75]">Atualização em tempo real, do novo ao concluído.</p></div><div className="mt-6 flex flex-col gap-3"><label className="relative block"><Search className="pointer-events-none absolute left-4 top-1/2 size-4 -translate-y-1/2 text-[#a62c63]" /><span className="sr-only">Procurar pedido</span><input aria-label="Procurar pedido" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Procurar por número, código, cliente ou WhatsApp" className="h-12 w-full rounded-full border border-[#82204f]/15 bg-white pl-11 pr-4 text-sm font-bold outline-none focus:border-[#82204f] focus:ring-2 focus:ring-[#82204f]/15" /></label><div className="flex gap-2 overflow-x-auto pb-2">{filters.map((status) => <button key={status} onClick={() => setFilter(status)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-black ${filter === status ? 'bg-[#351924] text-white' : 'bg-white text-[#6f5360]'}`}>{status === 'ACTIVE' ? 'Em andamento' : statusLabel[status]}</button>)}</div></div>{error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-5 overflow-hidden rounded-[24px] bg-white shadow-sm"><div className="hidden grid-cols-[130px_1fr_130px_130px_120px] gap-4 border-b px-5 py-3 text-xs font-bold uppercase tracking-wider text-[#826a75] md:grid"><span>Pedido</span><span>Cliente</span><span>Recebimento</span><span>Status</span><span className="text-right">Total</span></div>{visible.map((order) => <a key={order.id} href={`/admin/pedidos/${order.id}`} className="grid gap-2 border-b border-[#82204f]/8 p-5 transition last:border-0 hover:bg-[#fffaf5] md:grid-cols-[130px_1fr_130px_130px_120px] md:items-center md:gap-4"><div><strong className="block text-lg md:text-sm">{order.orderNumber}</strong><span className="text-[11px] text-[#826a75]">{order.createdAt?.toDate().toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}</span></div><span className="text-sm font-bold">{order.customer.name}</span><span className="text-xs text-[#826a75]">{order.fulfillment.mode === 'PICKUP' ? 'Retirada' : 'Delivery'}</span><span className={`w-fit rounded-full px-2.5 py-1 text-[11px] font-black ${order.status === 'NEW' ? 'bg-amber-100 text-amber-800' : order.status === 'CANCELLED' ? 'bg-red-100 text-red-700' : 'bg-[#fff0f5] text-[#82204f]'}`}>{statusLabel[order.status]}</span><strong className="md:text-right">{formatBRL(order.pricing.totalCents)}</strong></a>)}{!visible.length && <div className="p-10 text-center text-sm text-[#826a75]">Nenhum pedido encontrado.</div>}</div></AdminShell>;
}
