'use client';

import { ArrowRight, Clock3, MapPin } from 'lucide-react';
import { PublicHeader } from '@/components/public-header';
import { useCatalog } from '@/components/providers';
import { Button } from '@/components/ui/button';
import { formatBRL, isStoreOpen } from '@/shared/domain';

export default function Home() {
  const { catalog, config, loading, error, development } = useCatalog();
  const products = catalog.products.filter((product) => product.active).sort((a, b) => a.displayOrder - b.displayOrder);
  const open = config.orderingEnabled && (!config.enforceHours || isStoreOpen(new Date(), config));
  const primary = products.find((product) => product.productType === 'CUSTOMIZABLE') ?? products[0];
  return <main className="min-h-screen bg-[#fffaf5] text-[#2b1722]">
    <PublicHeader />
    <section className="relative overflow-hidden border-b border-[#82204f]/10"><div className="absolute -right-32 -top-28 size-80 rounded-full bg-[#ffcf3d]/25 blur-3xl" /><div className="absolute -bottom-44 left-1/3 size-80 rounded-full bg-[#d7f04a]/20 blur-3xl" /><div className="mx-auto grid max-w-6xl items-center gap-8 px-4 py-10 sm:px-6 sm:py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-20">
      <div className="relative z-10"><div className={`mb-5 inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-bold ${open ? 'border-emerald-700/15 bg-emerald-50 text-emerald-800' : 'border-amber-700/15 bg-amber-50 text-amber-900'}`}><span className={`size-2 rounded-full ${open ? 'bg-emerald-500' : 'bg-amber-500'}`} />{open ? 'Pedidos abertos agora' : config.pauseMessage || 'Pedidos fechados agora'}</div><h1 className="max-w-xl text-5xl font-black leading-[.94] tracking-[-0.06em] text-[#53142f] sm:text-6xl lg:text-7xl">Monte do seu jeito.</h1><p className="mt-5 max-w-md text-lg leading-relaxed text-[#6f5360]">Escolha o tamanho, seus favoritos e pronto. Seu pedido chega organizado direto para a nossa equipe.</p><Button disabled={!open || !primary} className="mt-7 h-13 rounded-full bg-[#82204f] px-6 text-base font-bold text-white shadow-[0_14px_30px_rgba(130,32,79,.24)] hover:bg-[#6d183f]" render={<a href={primary ? `/montar/${primary.id}` : '#produtos'} />}>
        Montar meu açaí <ArrowRight className="size-5" />
      </Button></div>
      <div className="relative mx-auto aspect-square w-full max-w-[430px]" aria-hidden="true"><div className="absolute inset-[6%] rotate-6 rounded-[38%_62%_52%_48%/47%_41%_59%_53%] bg-[#ffcf3d]" /><img src="/development-acai-placeholder.png" alt="" className="absolute inset-[13%] size-[74%] -rotate-3 rounded-[52%_48%_45%_55%/50%_47%_53%_50%] object-cover shadow-[0_30px_60px_rgba(83,20,47,.28)]" /><div className="absolute bottom-[7%] right-[2%] rounded-2xl bg-white px-4 py-3 shadow-xl"><strong className="block text-sm text-[#53142f]">Seu pedido</strong><span className="text-xs text-[#826a75]">do seu jeito • sem confusão</span></div></div>
    </div></section>
    <section id="produtos" className="mx-auto max-w-6xl px-4 py-10 sm:px-6 sm:py-14"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#a62c63]">Peça agora</p><h2 className="mt-2 text-3xl font-black tracking-[-0.04em] text-[#351924]">Escolha por onde começar</h2></div>{development && <span className="hidden rounded-full bg-[#fff0f5] px-3 py-1.5 text-xs font-bold text-[#82204f] sm:block">Dados de desenvolvimento</span>}</div>
      {loading && <div className="mt-7 grid gap-4 sm:grid-cols-2"><div className="h-52 animate-pulse rounded-[28px] bg-[#82204f]/8" /><div className="h-52 animate-pulse rounded-[28px] bg-[#82204f]/8" /></div>}
      {error && <div role="alert" className="mt-6 rounded-2xl bg-red-50 p-4 text-sm text-red-800">Não foi possível carregar o cardápio: {error}</div>}
      {!loading && !products.length && <div className="mt-7 rounded-[28px] border border-dashed border-[#82204f]/25 bg-white p-8 text-center"><strong>Cardápio em configuração</strong><p className="mt-1 text-sm text-[#826a75]">A loja ainda não publicou produtos.</p></div>}
      <div className="mt-7 grid gap-4 sm:grid-cols-2">{products.map((product) => { const starting = Math.min(...product.sizes.filter((size) => size.active).map((size) => size.basePriceCents)); return <a key={product.id} href={`/montar/${product.id}`} className="group grid min-h-48 grid-cols-[1fr_112px] overflow-hidden rounded-[28px] border border-[#82204f]/10 bg-white p-5 shadow-[0_12px_40px_rgba(88,32,58,.07)] transition hover:-translate-y-0.5 hover:shadow-[0_18px_45px_rgba(88,32,58,.12)] sm:grid-cols-[1fr_150px]"><div className="flex flex-col"><span className="text-xs font-bold text-[#a62c63]">{catalog.categories.find((category) => category.id === product.categoryId)?.name ?? 'Produto'}</span><h3 className="mt-2 text-xl font-black tracking-[-0.03em] text-[#351924]">{product.name}</h3><p className="mt-2 text-sm leading-relaxed text-[#826a75]">{product.description}</p><span className="mt-auto pt-5 text-sm font-extrabold text-[#82204f]">A partir de {formatBRL(starting)}</span></div><div className="relative overflow-hidden rounded-[22px] bg-gradient-to-br from-[#74204c] via-[#a22862] to-[#d14e7e]">{product.imageUrl && <img src={product.imageUrl} alt="" className="size-full object-cover opacity-85 transition group-hover:scale-105" />}<span className="absolute bottom-3 right-3 grid size-9 place-items-center rounded-full bg-[#d7f04a] text-[#351924]"><ArrowRight className="size-4" /></span></div></a>; })}</div>
      <div className="mt-8 grid gap-3 rounded-[28px] bg-[#351924] p-5 text-white sm:grid-cols-2 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-white/10"><Clock3 className="size-5 text-[#ffcf3d]" /></span><div><strong className="block text-sm">Horário da loja</strong><span className="text-xs text-white/60">Configurado e validado no pedido</span></div></div><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-white/10"><MapPin className="size-5 text-[#d7f04a]" /></span><div><strong className="block text-sm">{config.fulfillmentModes.includes('DELIVERY') ? 'Retirada e entrega' : 'Retirada'}</strong><span className="text-xs text-white/60">{config.city || 'Consulte as informações da loja'}</span></div></div></div>
    </section>
  </main>;
}
